env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - eslint-config-next
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
rules: {
  indent: ['error', 2],
  comma-dangle: ['error', {
    'objects': 'always-multiline',
    'arrays': 'always-multiline',
    'imports': 'always-multiline',
    'exports': 'always-multiline',
    'functions': 'only-multiline',
  }],
  jsx-quotes: ['warn', 'prefer-single'],
  react/react-in-jsx-scope: 'off',
  react/self-closing-comp: ['warn'],
  react/jsx-closing-bracket-location: ['warn', 'tag-aligned'],
  react/jsx-closing-tag-location: ['warn'],
  react/jsx-indent: ['warn', 2],
  react/jsx-tag-spacing: ['warn', {
    'closingSlash': 'never',
    'beforeSelfClosing': 'always',
    'afterOpening': 'never',
    'beforeClosing': 'never'
  }],
  '@typescript-eslint/comma-dangle': 'off',
  '@typescript-eslint/no-unused-vars': 'warn',
  '@typescript-eslint/triple-slash-reference': 'off',
  '@typescript-eslint/no-misused-promises': ['error', { 'checksVoidReturn': { 'attributes': false } }],
  '@typescript-eslint/naming-convention': 'off',
  '@typescript-eslint/consistent-type-definitions': ['warn', 'type']
}
