env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - eslint-config-next
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
rules: {
  react/react-in-jsx-scope: 'off',
  indent: ['error', 2],
  comma-dangle: ['error', {
    'objects': 'always-multiline',
    'arrays': 'always-multiline',
    'imports': 'always-multiline',
    'exports': 'always-multiline',
    'functions': 'only-multiline',
  }],
  '@typescript-eslint/comma-dangle': 'off',
  '@typescript-eslint/no-unused-vars': 'warn',
  '@typescript-eslint/triple-slash-reference': 'off',
  '@typescript-eslint/no-misused-promises': [2, { 'checksVoidReturn': { 'attributes': false } }],
  '@typescript-eslint/naming-convention': 'off',
  '@typescript-eslint/consistent-type-definitions': ['warn', 'type'],
  react/jsx-closing-bracket-location: [1, 'line-aligned']
}
